#!/usr/bin/env python3
"""Generate Finshield's subpages from shared partials.

The generated .html files are committed, so the site needs no build step to
view. Re-run this script after editing page content:

    python3 tools/build.py
"""
from pathlib import Path

from pages import PAGES

ROOT = Path(__file__).resolve().parent.parent

NAV = [
    ("products.html", "Products"),
    ("features.html", "Features"),
    ("benefits.html", "Benefits"),
    ("partners.html", "Partners"),
]

FOOTER_COLS = [
    ("Features", [
        ("analytics.html", "Analytics"),
        ("collaboration.html", "Collaboration"),
        ("data-management.html", "Data Management"),
        ("integrations.html", "Integrations"),
        ("security.html", "Security"),
    ]),
    ("Company", [
        ("about.html", "About us"),
        ("blog.html", "Blog"),
        ("careers.html", "Careers"),
        ("cookie-policy.html", "Cookie Policy"),
    ]),
    ("Resource", [
        ("customers.html", "Customers"),
        ("strategic.html", "Strategic"),
        ("guides.html", "E-books &amp; Guides"),
        ("webinar.html", "Webinar"),
    ]),
    ("Support", [
        ("help-center.html", "Help Center"),
        ("contact.html", "Contact"),
    ]),
]

LOGO_SVG = (
    '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 2 3 5.5v6.2c0 5 3.8 9.4 9 10.3 '
    '5.2-.9 9-5.3 9-10.3V5.5L12 2Z" fill="currentColor"/><path d="M8 12.2l2.7 2.7L16.3 9" '
    'fill="none" stroke="#000" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round"/></svg>'
)


def nav(active):
    current = ' class="active" aria-current="page"'
    links = "".join(
        f'<li><a href="{href}"{current if href == active else ""}>{label}</a></li>'
        for href, label in NAV
    )
    return f"""<nav class="nav container">
      <a href="index.html" class="logo" aria-label="Finshield home">{LOGO_SVG}finshield</a>
      <button class="nav-toggle" aria-label="Toggle menu" aria-expanded="false"><span></span><span></span></button>
      <ul class="nav-links">{links}</ul>
      <a href="signup.html" class="nav-signup">Sign up <span class="arrow">↗</span></a>
    </nav>"""


def footer():
    cols = "".join(
        f'<div class="footer-col"><h5>{title}</h5>'
        + "".join(f'<a href="{h}">{l}</a>' for h, l in links)
        + "</div>"
        for title, links in FOOTER_COLS
    )
    return f"""<footer class="footer">
    <div class="giant" aria-hidden="true">finshield</div>
    <div class="container">
      <div class="socials">
        <a href="https://facebook.com" aria-label="Facebook">f</a>
        <a href="https://instagram.com" aria-label="Instagram">◎</a>
        <a href="https://x.com" aria-label="X">𝕏</a>
        <a href="https://linkedin.com" aria-label="LinkedIn">in</a>
      </div>
      <div class="footer-grid">
        <div class="footer-cta">
          <h2>Ready to take<br />control of your<br />financial future</h2>
          <a href="signup.html" class="btn btn-white btn-sm">Get Started</a>
        </div>
        {cols}
      </div>
      <div class="footer-bottom">
        <span>© <span id="year">2024</span> Finshield</span>
        <span>All Rights Reserved</span>
        <span class="legal"><a href="terms.html">Terms of Service</a><a href="privacy.html">Privacy Policy</a></span>
      </div>
    </div>
  </footer>"""


def render(page):
    return f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>{page["title"]} — Finshield</title>
  <meta name="description" content="{page["description"]}" />
  <link rel="icon" href="assets/logo.svg" type="image/svg+xml" />
  <link rel="preconnect" href="https://fonts.googleapis.com" />
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
  <link href="https://fonts.googleapis.com/css2?family=Archivo:wght@500;700;800;900&family=Manrope:wght@400;500;600;700&display=swap" rel="stylesheet" />
  <link rel="stylesheet" href="styles.css" />
</head>
<body class="subpage">
  <!-- Generated by tools/build.py — edit tools/pages.py, not this file. -->
  <header class="page-top dark">
    {nav(page.get("active"))}
    {page["hero"]}
  </header>

  <main>
{page["body"]}
  </main>

  {footer()}

  <script src="script.js"></script>
  <script src="motion.js"></script>
</body>
</html>
"""


def main():
    for filename, page in PAGES.items():
        (ROOT / filename).write_text(render(page))
        print("wrote", filename)


if __name__ == "__main__":
    main()
